spring:
  application:
    name: zuul

server:
  port: 8012

eureka:
  server:
    port: 8010
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:123456@${eureka.instance.hostname}:${eureka.server.port}/eureka/
# 网关路由
zuul:
  prefix: /api
  #排除某几个服务
  #ignored-services: service-provider1
  routes:
    #URL指定路由方法（和prefix冲突不能同时存在）
    #service-provider:
    #  path: /service-provider/**
    #  url: http://127.0.0.1:8011/
    #服务指定路由方法1（和prefix冲突不能同时存在）
    #service-provider:
    #  path: /service-provider/**
    #  serviceId: service-provider1
    #服务指定路由方法2（简化配置）
    #service-provider1:
    #  path: /service-provider/**
    sp1: #这个地方的值是可以任意的字符串
      path: /sp1/** #映射路径
      serviceId: service-provider1 #服务的spring.application.name
#为服务Id名称为service-provider1的项目配置负载均衡策略为随机
service-provider1:
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#暴露actuator的所有端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#设置springboot日志级别
logging:
  level:
    root: debug
