spring:
  application:
    name: eureka-server1

server:
  #端口号
  port: 8010

eureka:
  instance:
    #集群中实例名称要唯一
    hostname: eureka1
  client:
    #是否将自己注册到Eureka Server
    registerWithEureka: true
    #是否从Eureka Server获取注册信息
    fetchRegistry: true
    serviceUrl:
      #配置其他集群的地址进行相互注册
      defaultZone: http://eureka2:8009/eureka/,http://eureka3:8008/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 10000 #清理间隔（单位毫秒）

#暴露actuator的所有端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
